name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test
        run: |
          bash test/runtests.sh
      - name: Report test results as Annotations
        if: ${{ always() }}
        uses: guyarb/golang-test-annoations@v0.6.0
        with:
          test-results: test/results.json
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: 'test-report'
          path: ${{ github.workspace }}/test
      - name: Get code coverage
        uses: codecov/codecov-action@v3
